#!/usr/bin/python3

import tkinter as tk
from tkinter import filedialog
import subprocess as sp
from pathlib import Path
import shlex


def select_folder(foldertype):
    # Create a hidden root window (to prevent a blank Tk window from appearing)
    root = tk.Tk()
    root.withdraw() 

    # Open the directory selection dialog
    path = filedialog.askdirectory(
        title="Seleziona la {}".format(foldertype)
    )

    # Destroy the hidden window after selection
    root.destroy()

    # adapt 
    folder_path = shlex.quote(str(path))

    return folder_path

def main():

    # Call the function to run the dialog
    SRC = select_folder("Fonte")
    if not SRC: return 1    
    
    DEST = select_folder("Destinazione")
    if not DEST: return 1
    
    runstring = "rsync -a --safe-links --fsync --info=PROGRESS2,STATS2,NONREG0 {} {}".format(SRC, DEST)
    sp.run(runstring, shell=True)

if __name__ == "__main__":
    main()

